# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectorCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorNoncomp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryCommodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryMake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryNoncomp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.IntegerField()),
                ('row', models.IntegerField()),
                ('val', models.DecimalField(decimal_places=10, max_digits=19)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
